spacetelescope/spaceKLIP

- spaceKLIP/companion.py
- spaceKLIP/contrast.py
- spaceKLIP/engine.py
- spaceKLIP/io.py
- spaceKLIP/plotting.py
- spaceKLIP/rampfit.py
- spaceKLIP/utils.py
- tests/example_config.yaml
- tests/run_pipeline.py
A couple of quick fixes:
- Specifiying run directories will now correctly use that run directory, OR if the run directory is invalid then no folder will be created and warning will be shown. If the rundir list is empty, then all run directories are used. 
- Fixed the _inj plot from the calibrated contrast stage.
> Fix specification of run directories

- README.rst
CRDS environment variables are necessary to get spaceKLIP to run successfully. I've added a note and a link to the readme.
> add note about CRDS variables

- .gitignore
- spaceKLIP/psf.py
- spaceKLIP/rampfit.py
- spaceKLIP/utils.py
Created a new JWST pipeline class called `Coron1Pipeline` (which is a subclass of `Detector1Pipeline`) into rampfit.py. This new class is called in place of `Detector1Pipeline`. It can act in the same way, but some pipeline defaults have been changed to better reflect possible improvements for coronagraphic data. As calibration files improve (e.g., higher SNR dark cals), the `Coron1Pipeline` can get modified. I’ve replaced the call to Detector1Pipeline with this class. 
New defaults include:
1. perform a pseudo-reference correction (number of top/bottom rows are set by a class attribute `nrow_ref`). Setting `nrow_ref=0` will disable this option. Default value is 20.
2. turn off diagonal growing for saturation pixels (still does horizontal/vertical crosses) using the attribute …
> Coron1Detector subclass for ramp fitting

- spaceKLIP/companion.py
- spaceKLIP/engine.py
- spaceKLIP/io.py
- spaceKLIP/psf.py
- spaceKLIP/utils.py
- tests/nircam_config.yaml
- tests/run_pipeline.py
Default generation of the offset psf is based off a 5700K blackbody, which can generate clear differences in the PSF compared to generating it from an input planetary spectrum. Now added the ability to generate offset psf's using a `psf_spec_file` attribute. File must be provided in micron, Jy
> Adding ability to generate offsetpsf using from input spectrum

- spaceKLIP/companion.py
- spaceKLIP/contrast.py
- spaceKLIP/psf.py
- spaceKLIP/subtraction.py
- spaceKLIP/utils.py
- tests/miri_config.yaml
- tests/nircam_config.yaml
- tests/run_pipeline.py
Small update (must have updated pyKLIP to the latest jwst branch too) that allows you to perform some Gaussian blurring to the input images for PSF subtraction, and companion injection/fitting. 
All done through the `blur_images` attribute in the config file. Future development could be to only use the blurring for specific things. Helps a lot with Fourier artifacts in the F250M data.
> Adding gaussian blurring

- spaceKLIP/engine.py
- spaceKLIP/io.py
- spaceKLIP/rampfit.py
Previously, references were identified by the presence of small grid dithers. However, some science observations will have SGDs defined. In addition, there is an ISPSF header keyword used to identify if an observation is a reference target. I have updated the code to first look for the ISPSF header keyword and flag observations as either science or reference based on this header value. However, most simulated data do not have this keyword, so if not found, spaceKLIP will fall back to the previous method of looking for multiple dither positions to identify reference targets.
> Automatic identification of reference target

- docs/source/index.rst
- docs/source/tutorials/Introduction.ipynb
- spaceKLIP/engine.py
- spaceKLIP/io.py
A couple semi-related additions: 
- Adds a new docs page with a (partial) big picture introduction to some of the concepts and how files are organized. This is just a starting point of course
- Adds support for environment variables in paths
- As part of not-yet-complete work to update the 01_quickstart notebook using the simulated data, add some flexibility to the sort_files function to help it work on the simulated data. Also add more verbose outputs for debugging, optionally.
> Dev/mdp: add docs overview page, and add support for environment variables in paths

- docs/source/Attribution.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/spaceKLIP.rst
Updates docs framework with sphinx-apidoc. Add citation information. 
Replaces https://github.com/kammerje/spaceKLIP_new/pull/23 from the spaceklip_new repo
> start updating docs for spaceklip 2.0

- .github/workflows/ci_workflows.yml
Update URL in the CI testing config to get the latest version of the data files. Needed fix for the CI.
> update URL for most recent version of webbpsf data files

- spaceKLIP/analysistools.py
- spaceKLIP/database.py
- spaceKLIP/imagetools.py
- spaceKLIP/pyklippipeline.py
Made improvements to general book keeping for a few things.
1) XOFFSET and YOFFSET are now always recorded in arcseconds. This is the same unit that the default pipeline uses and will ensure future compatibility with the newer version of pyKLIP. 
2) BLURFWHM is now always recorded as the FWHM, and not sigma, of the Gaussian to use for blurring. Additionally, adjusted how the blur is applied when scaling the resolution during the contrast curve calculation. 
Checked with the NIRCam ERS F300M data and looks like the resolution of the contrast curves is being correctly adjusted now. Resolves #93
> Bookkeeping

- spaceKLIP/imagetools.py
- spaceKLIP/pyklippipeline.py
A few additions to image tools. 
1. New function `subtract_1overf_stripe_noise` that subtracts the horizontal stripes from 1 over f noise. The method used is specialized for coronagraphic imaging, which may have large regions of the detector full of bright starlight such that a simple median of rows does not work, and even a masked or robust sigma-clipped median may not be very effective. But for coronagraphy we can rely on often having many ints all at the same telescope pointing, which enables using a comparison between each int and the median int to help remove starlight and allow a cleaner measurement of the 1/f noise. Results as shown in the attached plot. 
2. Update `subtract_median` to have an option to select between a few alternative algorithms, in particular a plain median vs a …
> add subtract_1overf_stripe_noise and a few other imagetools enhancement

- spaceKLIP/coron1pipeline.py
- spaceKLIP/fnoise_clean.py
- spaceKLIP/imagetools.py
- spaceKLIP/logging_tools.py
Part 1 of #98.
Added a number of updates to the default coron1pipeline, most importantly the exclusion of dark subtraction for subarrays. This is implemented through a new function `run_single_file` which sets a number of best-practice defaults, such as skipping darks, IPC, and persistence steps. It also sets some defaults for jump thresholds, saturation flagging parameters, and pseudo-ref pixel rows / columns. `run_obs` now calls `run_single_file`. 
All of the changes here should not change the outcome of existing notebooks and scripts. The only thing I've done is include better defaults, added more options for simplicity, debugging, and and fixed some known bugs within the pipeline itself.
New pipeline options:
- Can now save intermediate step files via `pipe.save_intermediates=True`. …
> Part 1 of #98 - Updates to coron1pipeline

- spaceKLIP/coron1pipeline.py
- spaceKLIP/fnoise_clean.py
- spaceKLIP/imagetools.py
Part 4 of #98
Correct 1/f noise striping in stage1:
- Create fnoise_clean.py file that houses code for fitting a 1/f noise model to data and iteratively masks outlier pixels.
- Add `cube_fit` function, which utilizes polynomial fitting routines from `webbpsf_ext` to fit linearized unsaturated and unflagged pixel data to quickly generate a kTC bias and slope images.
- Utilize `cube_fit` to create kTC bias to subtract from linearized ramp data to create clean group-level data
- The slope images from `cube_fit` are then averaged together and used to produce a high-SNR ramp such that group signal levels match those within a given integration. 
- Use 1/f noise filtering algorithm on group level data to model the spatial 1/f striping and subtract it. 
1/f cleaning routine adds about 100 msec …
> Part 4 of #98 - 1/f Noise Correction

- spaceKLIP/database.py
- spaceKLIP/utils.py
Part 2 of #98
This is a minor update for grabbing filter information during init:
- falls back to `webbpsf` filters if the SVO database cannot be reached. 
Rewrote COM throughput function:
- The `get_tp_comsubst` function now uses `webbpsf_ext`'s built-in bandpass functionality to recover COM transmission across a filter bandpass. The throughputs in `webbpsf_ext` have been corrected based on ISIM CV3 measurements. For the sake of consistency, I think it is better to use these instead of the older 2015 transmission file.
> Part 2 of #98 - Filter calls to SVO database

- spaceKLIP/coron1pipeline.py
- spaceKLIP/coron2pipeline.py
- spaceKLIP/plotting.py
Changes to `runobs`:
- Calls `run_single_file` similar to those in #99 
- Added various verbosity options for those who dislike the deluge of log outputs
- `verbose` keyword set to True shows everything at INFO level or above from the pipeline. Setting this to False will show various SpaceKLIP log messages, but suppress pipeline message below ERROR.
- `quiet` suppresses all messages below ERROR and employs progress bars to keep track of data reduction progress.
- Skip pipeline processing if data results already exist in output directory rather than re-running unnecessary and overwriting. Can be overriden using the `overwrite` keyword.
- Add option to also process rate->cal in addition to the rateints data products.
Miscellaneous
- If outlier detection was run but intermediates were not …
> Part 5 of #98 - Updates to stage2 pipeline calls

- spaceKLIP/coron1pipeline.py
- spaceKLIP/fnoise_clean.py
- spaceKLIP/utils.py
Removed the SavGol 1/f correction code from the pipeline and packaged it all into a jwst `Step` class and placed in the `fnoise_clean.py` file. Now this works similarly to other steps within jwst pipelines. Similarly created and added a kTC subtraction Step class `kTCSubtractStep`. Overall, the PR shouldn't change anything to the outputs or results, but simply cleans up the pipeline code and allows reuse of the 1/f correction for other pipelines.
Vertical striping correction is now applied in the `CleanSubarry` class and can be turned off and on in the `OneOverfStep` class via the `vertical_corr` parameter. (e.g., `pipeline.subtract_1overf.vertical_corr`). This has been turned on by default.
Full frame subarrays are now cleaned more intelligently via the implementation of the …
> Create 1/f noise correction Step class

- spaceKLIP/analysistools.py
- spaceKLIP/imagetools.py
- spaceKLIP/pyklippipeline.py
After discussions with the NIRCam Team we are removing the COM substrate correction as it had already been accounted for in the JWST pipeline photometric calibration (@mperrin @AarynnCarter).
> Removing COM substrate correction & bugfix with phase_cross_correlation

- docs/source/tutorials/MAST query tools for coronagraphic datasets.ipynb
- spaceKLIP/mast.py
This PR enhances the `mast.query_coron_datasets` function to allow querying on more parameters, and to optionally return a more detailed table including individual filenames (The prior behavior to return a shorter summary table remains the default). 
In addition there is a new `download_files` function that retrieves from MAST based on the query results. 
Example usage: 
```
> table = spaceKLIP.mast.query_coron_datasets('NIRCam', program=1386, filt='F444W', kind='SCI', 
return_filenames=True, level='uncal')
> spaceKLIP.mast.download_files(table)
DOWNLOAD SUCCESSFUL: ./jw01386002001_0310a_00001_nrcalong_uncal.fits
DOWNLOAD SUCCESSFUL: ./jw01386003001_0310a_00001_nrcalong_uncal.fits
```
> enhance MAST query interface and add download capabilities

- readthedocs.yml
Minor but required update as per https://blog.readthedocs.com/use-build-os-config/
For the record here's a copy of the auto notification email I got from RTD. (Does anyone other than me get the RTD emails for this package, by the way? ) 
<blockquote>
Hello,
The build.image config key on .readthedocs.yaml has been deprecated, and will be removed on October 16, 2023. We are sending weekly notifications about this issue to all impacted users, as well as temporary build failures (brownouts) as the date approaches for those who haven't migrated their projects. The timeline for this deprecation is as follows:
* Monday, August 28, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)
* Monday, September 18, 2023: Do a second brownout …
> update readthe docs config 

- spaceKLIP/coron2pipeline.py
The `coron2pipeline` has options to save intermediate data products. However, the `save_intermediates` attribute is not actually defined during init (it has has instead been defined during SpaceKLIP's higher level calls, though). This fix adds it to the class init with a default value of `False`.
> coron2pipeline save_intermediates

- spaceKLIP/database.py
- spaceKLIP/imagetools.py
- spaceKLIP/plotting.py
Some small edits while re-testing the NIRCam reduction notebook in preparation for testing the #91 PR. 
- fix error with return_error parameter for versions of skimage < 0.22
- enhance create_database func to allow reading in level 3 data, via a new `readlevel3=True` parameter that invokes `read_s3_data` if needed.
- Fix some minor bugs in the display functions that are used in that tutorial notebook
> minor fixes & enhancements while testing the tutorial notebook

- readthedocs.yml
I already implemented this change on develop in #104, but to get RTD working again we need this change on `main`, it turns out. 
Rather than waiting for whenever we next merge develop to main, it's better to just do this as a fix directly to main now.
> update readthedocs config on main

- readthedocs.yml
Same as #123, but this time actually pointing to `main`.
> update readthedocs config on main, actually on main

- readthedocs.yml
remove unnecessary/deprecated python.version parameter, based on error message from latest RTD build.
> More RTD config debugging

- docs/source/conf.py
In docs conf.py, use pkg_resources  to avoid package import which would needs all webbpsf data files etc. Currently, the import spaceKLIP part is erroring out on RTD for not having those data files.
> more readthedocs config debugging

- spaceKLIP/fnoise_clean.py
During 1/f noise correction step, rather than masking any pixel with some DQ flag as a bad pixel, only use the DO_NOT_USE values. Otherwise, some benign DQ flags (such as unstable bias) could flag the entire image as full of bad pixels.
> Better handling of bad pixel masking

- examples/example_miri_sky_1386.py
- examples/example_nircam_sim_1441.py
- examples/example_nircam_sky_1386.py
- examples/example_nircam_sky_1441.py
- examples/example_niriss_sky_1093.py
- spaceKLIP/analysistools.py
- spaceKLIP/classpsfsubpipeline.py
- spaceKLIP/coron1pipeline.py
- spaceKLIP/coron2pipeline.py
- spaceKLIP/coron3pipeline.py
- spaceKLIP/database.py
- spaceKLIP/fnoise_clean.py
- spaceKLIP/imagetools.py
- spaceKLIP/make_psfmasks.py
- spaceKLIP/plotting.py
- spaceKLIP/psf.py
- spaceKLIP/pyklippipeline.py
- spaceKLIP/sk_style.mplstyle
- spaceKLIP/starphot.py
- spaceKLIP/utils.py
`import spaceKLIP` should not have side effects that unexpectedly change the appearance of plots produced by other non-spaceKLIP code. In particular we shouldn't hard-code overrides to a user's default matplotlib settings in rcParams.
> Avoid changing matplotlib rcParams font size

- spaceKLIP/utils.py
I created a couple utility functions for interpreting DQ masks and their flags. 
1. `interpret_dq_value(dq_value)` will parse out a value from the DQ array into various bits and show their human-readable mnemonic as a set. This just wraps the `interpret_dq_value` from the pipeline.
```  python
res = interpret_dq_value(16387)
```
2. `get_dqmask(dq_arr, bitvalues)` will create a binary boolean mask from a DQ array. For instance, if someone wanted to find all pixels that were flagged as RC pixel as well as saturated within a DQ array, you would say:
```  python
mask = get_dqmask(dq_arr, [2, 2**14])
```
> DQ flags and masks

- requirements.txt
- spaceKLIP/coron2pipeline.py
- spaceKLIP/plotting.py
- spaceKLIP/wcs_utils.py
Instead of requiring users to install all of jdaviz (which has a very large number of dependencies) simply for a compass plotting tool, I copied over the standalone `wcs_utils.py` file which houses the WCA coordinate transformation used by jdaviz to plot the compass. This was originally adapted from Ginga (ginga.util.wcs, ginga.trcalc, and ginga.Bindings.ImageViewBindings).
I'm not sure what the software licensing rules are here, but I would rather figure out a way of ditching jdaviz import since it's not used for anything other than plotting some compass symbols.
> Remove jdaviz

- spaceKLIP/fnoise_clean.py
Quick fix to account for different naming conventions of multiprocess threads. Some versions of multiprocessing can spawn threads with the name "PoolWorker-N" as well as "Process-N". If we are already in such a spawned thread, then we should not run more new multiprocess threads. This expands the 1/f noise multiprocessing to check for such instances.
> multiprocess fix

- docs/source/_static/wider_docs.css
- docs/source/conf.py
- docs/source/tutorials/tutorial_MIRI_contrast_analyses.ipynb
- docs/source/tutorials/tutorial_MIRI_reductions.ipynb
- docs/source/tutorials/tutorial_NIRCam_contrast_analyses.ipynb
Adding a few changes to the readthedocs:
- Wider column width so images display properly / things aren't so condensed. 
- Adding direct links to tutorial notebooks at the top of each tutorial page
- Adjust tutorial alert blocks following: https://nbsphinx.readthedocs.io/en/0.9.3/markdown-cells.html
- Removing notebook display adjustment that caused images to not appear / be replaced by whitespace.
> Improving formatting for readthedocs tutorial notebooks

- docs/source/Installation-and-dependencies.rst
- docs/source/TLDR.rst
python=3 is insufficient in when creating the conda environment because 3.12 is not supported. 
Also, a final couple of installation steps should appear
> Update installation documentation for consistency and functionality

- spaceKLIP/imagetools.py
The `return_error` keyword has been removed from `phase_cross_correlation`:
https://scikit-image.org/docs/stable/api/skimage.registration.html#skimage.registration.phase_cross_correlation
Removing from our code too to avoid crashes. Previously we had this set to True, but it seems that this is returned regardless now, so no major changes needed.
> HOTFIX: Remove deprecated parameter from phase_cross_correlation

- requirements.txt
Edit: Sorry, not sure where the description went. 
stsci.stimage updated last week and the latest 0.2.7 version is causing our CI runs to crash due to failed import of a stsci.stimage function. I've looked at the update and don't see any major change or improvement that we should account for, so I think it makes sense to lock things at 0.2.6 until they push another update so that we can keep our updates moving. 
It seems they are already aware of the issue and have a PR in progress: https://github.com/spacetelescope/stsci.stimage/pull/37
> Formalising stsci.stimage requirement due to recent update issues

- spaceKLIP/starphot.py
William: 
I'm getting an error in this line of starphot.get_stellar_magnitudes when trying to run extract_companions. I'm trying to figure out whether this is a bug I need to make an issue about or whether I've just mis-installed the new synphot/stsynphot/new webbpsf_ext.
input_flux = u.Quantity(spec.sp_model.flux, str(spec.sp_model.fluxunits))
ValueError: 'PHOTLAM' did not parse as unit
edit: input_flux = u.Quantity(spec.sp_model.flux, str(spec.sp_model.fluxunits).lower()) worked to fix this bug
Jarron:
yep, these are the fluxunits definitions in synphot.units:
PHOTLAM = u.def_unit(
'photlam', u.photon / (u.cm**2 * u.s * u.AA),
format={'generic': 'PHOTLAM', 'console': 'PHOTLAM'})
PHOTNU = u.def_unit(
'photnu', u.photon / (u.cm**2 * u.s * u.Hz),
format={'generic': 'PHOTNU', 'console': …
> photlam units need to be in lowercase

- spaceKLIP/plotting.py
The secondary axes (in arcsec) added to the figures overlap with the original pixel value tick marks. This addition to plotting.py will clear the pixel value tick marks before secondary axes get added to the figure.
> Cleared overlapping tick marks

- spaceKLIP/analysistools.py
- spaceKLIP/psf.py
Adds kwargs for each of the currently hard coded forward model variables, as well as a kwarg to specify an input planetary spectrum when generating the psf in `extract_companions`. 
I tested this on the ERS F444W dataset and reproduced the expected behavior of `extract_companions` in this case. Example kwargs:
```
Analysis.extract_companions(companions, 
starfile, 
mstar_err, 
klmode=5,
spectral_type='A2V', 
fitmethod='mcmc',
fitkernel='diag',
subdir='companions',
planetfile='./HIP65426b_BTSETTL_SCALED_MU_JY.txt',
boxsize=30,
dr=3,
exclr=3,
xrange=3,
yrange=3,
frange=[-1e-1,1e1],
nthreads=16,
corr_len_range=[-10,10]
)
```
Turns out you get different values comparing the develop behavior vs this branch's behavior using an appropriate temperature spectrum for a bright enough companion. …
> Add kwargs for forward modeling variables, input planet spectrum for psf gen

- spaceKLIP/imagetools.py
See discussion in #114 . For data with more complex speckle patterns (e.g. NIRCam bar NARROW coronagraphy), it can be necessary to emphasize the speckle pattern itself rather than the central leakage term. I've found a combination of two strategies reproduces the commanded shifts from the SGD: masking the central leakage using a custom mask during the `align_frames` step, and taking the square root of the images before cross correlation. This PR introduces non-intrusive toggles to do both of these things.
> Add sqrt_stretch and custom mask to align steps

- spaceKLIP/database.py
See discussion in #114 . For data affected by bad fits writing behavior, for instance, the NIRCam BAR/NARROW offset position, it might be necessary to toggle calling the CRPIX values from pysaif, as opposed to recording them from the headers. This affects the position of the mask and therefore the coronagraphic throughput. Default behavior is unchanged and the toggle is set to false. Added to the appropriate functions in `database.py`
Potential improvement could look to incorporate @JarronL 's `webbpsf_ext.imreg_tools.get_coron_apname` function in the default database building step, but this change is non-intrusive and sufficient for current reductions (unlike the original implementation in #114 ).
> Determine crpix from saif toggle

- spaceKLIP/analysistools.py
just a quick update to return the "resolution" variable units to exclusion radius expression. having too large of an exclr term will return errors when sampling otherwise. sorry for missing this in the previous analysistools update PR!
> update default exclusion radius units

- spaceKLIP/coron1pipeline.py
- spaceKLIP/coron2pipeline.py
- spaceKLIP/utils.py
- JWST pipeline version 1.15.0 / stpipe 0.6.0 has removed the Step.closeout() function, which raises an AttributeError. This PR catches this if needed. 
- This PR also converts scipy.integrate.simps calls to scipy.integrate.simpson, as the naming has been changed. 
Resolves #197
> Resolving deprecation of Step.closeout() method

- spaceKLIP/imagetools.py
Adding function to perform MCMC fitting with a psf convolved by a gaussian
> Merging gs-inject-source into develop

- spaceKLIP/coron1pipeline.py
Work around for known bug when performing multiprocessing with OLS_C fitting (https://github.com/spacetelescope/jwst/issues/8842 and https://github.com/spacetelescope/jwst/issues/8710) by defaulting to 1 python process during ramp fitting. In addition, this provides slightly better performance during the ramp-fitting process for the C-fitting routine:
- stage 1 pipeline v1.15.1 with maximum_cores='none': 2m57sec
- stage 1 pipeline v1.15.1 with maximum_cores='quarter': 3m15sec
- stage 1 pipeline v1.15.1 with maximum_cores='half': 3m22sec
It appears that memory transfer oveheads for python multiprocessing actually slows down the fitting process. The OLS_C functionality inherently utilizing native multiprocessing without having to spawn new threads and is overall much faster when number of …
> default maximum_cores='none'

- spaceKLIP/database.py
When building a database with MIRI files, this step can be quite time-consuming. The code reads the data in by default even when the NINTS keyword is populated in the header. I added an if/else condition to handle this more efficiently.
> Fix to read in files faster

- spaceKLIP/analysistools.py
In AnalysisTools.calibrate_contast(), maxnumbasis is set as np.max(KL_modes), which in some cases is different than in pyklippipeline.get_pyklip_filepaths() where it is np.sum(nints), because some users may set their list of KL modes necessarily smaller than the max ints, but still find better contrast when constructing the i_th KL with a large number of  images. 
This fix simply implements get_pyklip_filepaths in calibrate_contrast to set maxnumbasis.
> Ensure maxnumbasis for cc is same as rc/klipsub

- spaceKLIP/imagetools.py
Fixes issue #140 by changing update_nircam_centers to use the most up-to-date SIAF/PRD mask position available along with filter specific offsets compiled in resources/filter_shifts_jarron.json. There should be no necessary changes in workflow, and this should produce correct results for all NIRCam coronagraphy — irrespective of when it was observed/downloaded. 
Note: for this implementation, when the database center is being used (because the file's PRD version is at least as new as the one being used by pysiaf OR because force_db_center is True), running this command two or more times will yield incorrect CRPIX values unless the filter offsets are zero. However, I think this is true for the current version as well.
> Fix for SW/LW mask offset inconsistency resulting from update_nircam_centers

- spaceKLIP/coron1pipeline.py
I needed to trim off the last (saturated) group for a certain observation, so I added a simple function/option based on the mask groups routines to mask an arbitrary number of groups in science or reference images in stage one. It will operate on SCI or REF data.
Usage:
```
coron1pipeline.run_obs(database=Database,
steps={
'mask_groups': {
'skip': False, 
'mask_method': 'custom',
'custom_group':16, # must be some integer-like corresponding to the maximum group you'd like included in your stage1 reduction
},
)
```
> mask given num of groups from any s1 sci/ref

- spaceKLIP/database.py
This pull request introduces a new method to the `spaceKLIP/database.py` file to adjust the directory paths of data products. The only change is the addition of the `adjust_dir` method, which allows for updating the directory paths of various data types within the database.
Key changes include:
* Added `adjust_dir` method to `spaceKLIP/database.py` to update directory paths for data products based on their type ('red', 'obs', or 'src'). The method updates the paths for 'FITSFILE' and 'MASKFILE' entries and raises a `UserWarning` if the directory is invalid.
> Adjust database path

- spaceKLIP/analysistools.py
- spaceKLIP/database.py
- spaceKLIP/imagetools.py
- spaceKLIP/plotting.py
- spaceKLIP/psf.py
- spaceKLIP/pyklippipeline.py
Currently spaceKLIP tracks one pixel location `CRPIX1/2` and at different steps in the pipeline this can refer either to the location of the mask center or the star center. We add two additional header keywords (and associated table columns) to track the star location (`STARCENX/Y`) and the mask location (`MASKCENX/Y`). We have tested and confirmed the desired behavior on both NIRCam and MIRI ERS data.
*Note: This PR depends also on a PR to `pyklip` allowing the user to specify which header keyword to use as the star location for alignment and derotation purposes*
- `database.py `
- Added `MASKCENX/Y` and `STARCENX/Y` keywords as columns to be tracked in the database. These are 1-indexed pixel locations analogous to the `CRPIX1/2` column. 
- If not present in the input fits files, …
> Track Mask and Star Center Individually

- spaceKLIP/analysistools.py
- spaceKLIP/database.py
- spaceKLIP/imagetools.py
- spaceKLIP/pyklippipeline.py
- spaceKLIP/utils.py
Here are a list of the changes made:
- Renamed alignshift to align_shift for consistency with existing parameter names.
- Ensured that `STARCENX/Y` and `MASKCENX/Y` are properly 1-indexed before being written to FITS headers.
- Removed updates to `MASKCENX/Y` and `CRPIX1/2` in `calculate_alignment`, since this function no longer applies shifts directly—it now only records the required alignment shifts.
- Updated `STARCENX/Y` in `calculate_alignment` based on the median shift across all frames within each image. We update here because we have better idea of star's location (if not first science frame in database).
- Uncommented the plotting routine in `calculate_alignment`.
- Added logic in `calculate_centers` to write `CRPIX1/2` from the database into file header, supporting cases where …
> Updated for pull request 250
