spaceKLIP/companion.py, spaceKLIP/contrast.py, spaceKLIP/io.py, spaceKLIP/plotting.py, spaceKLIP/subtraction.py, spaceKLIP/utils.py, tests/example_config.yaml, tests/run_pipeline.py
Updating the main branch ahead of OWL, added a variety of functionality for MIRI data and made some tweaks to how data is saved. 
Resolve issue #23
=> Updating just before OWL

spaceKLIP/imgprocess.py, spaceKLIP/rampfit.py, tests/example_config.yaml, tests/run_pipeline.py
Add capability to define specific pixels (with indices as recorded in DS9) in a comma separated file, see attached for example.
Pixel routine just looks for neighbouring pixels to those defined, computes the median, and replaces the defined pixels with it. 
[pixmask_1140.txt](https://github.com/kammerje/spaceKLIP/files/9223690/pixmask_1140.txt)
=> Adding manual pixel correction

spaceKLIP/companion.py, spaceKLIP/imgprocess.py, spaceKLIP/utils.py, tests/nircam_config.yaml, tests/run_pipeline.py
There was a bug where the field dependent correction was being run on the WebbPSF_ext PSF model even though it's already incorporated into the simulation.
+ some edits from Max.
=> Fixing bug in companion.py

readthedocs.yml
Continued efforts to get doc build working.
=> Readthedocs should use development requirements for doc build

readthedocs.yml
Continued poking at things to try to get the RTD build working.
=> continued RTD config debugging

spaceKLIP/engine.py, spaceKLIP/imgprocess.py, spaceKLIP/io.py, spaceKLIP/subtraction.py
Add function `meta_checks` to perform checks on .yaml inputs.
Include MIRI filter checking prior to miri trim passthrough.
=> Meta check function / MIRI filter check

spaceKLIP/io.py
=> Keyword should be IS_PSF, not ISPSF

spaceKLIP/plotting.py
Copies (restores) the contents of `plotting.py` in version 1, and merges with the content in `plotting.py` in version 2. 
Only edits are some cleanup and reordering of the imports at the top. No edits or testing yet of the plotting code itself. 
**untested, no guarantees of working yet with v2**, but still in my opinion worth copying over directly and debugging later.
=> migrate the entire text of plotting.py from v1 to v2. 

requirements.txt
add missing requirements to requirements.txt. This is needed for imports to even build the docs
=> More RTD debugging, continued

docs/source/conf.py, readthedocs.yml, requirements.txt
These commits just got RTD builds working again on `main`. Adding to `develop` to for consistency.
=> Fix docs config in RTD, also on develop

docs/source/conf.py
=> Typo fix for RTD implementation

docs/source/conf.py, docs/source/modules.rst, docs/source/spaceKLIP.rst, requirements-dev.txt, spaceKLIP/classpsfsubpipeline.py, spaceKLIP/coron1pipeline.py, spaceKLIP/imagetools.py, spaceKLIP/plotting.py, spaceKLIP/pyklippipeline.py, spaceKLIP/utils.py
Okay, moved from `sphinx.ext.napoleon` to `sphinx_automodapi.automodapi` and think I can get the documentation to compile without explicitly trying to import and load all of our dependencies. Fingers crossed this makes the documentation compile.
Also fixed a bunch of small formatting mistakes.
=> Attempting to resolve readthedocs API issues

spaceKLIP/analysistools.py
Save info about starfile and spectral type separately, to enable using votable or txt starfiles in calibrate_contrast
=> Starfile analysis hotfix

spaceKLIP/mast.py
Some small/unrelated features added to the MAST query interface. 
- add parameter `ignore_exclusive_access` to filter out exclusive-access data (i.e. proprietary data), so that the query results only include data that can be freely downloaded by anyone. 
- add parameter `exp_type` to allow querying by the MAST exp_type field. 
- Add `observtn` (observation number) to the fields queried and returned from MAST. It was just an oversight to leave this out before.
=> Some small additions to query_coron_datasets

spaceKLIP/imagetools.py
hotfix for #187, uses solution from if statement directly above for sci plot colors. for large number of references, result is not pretty, but at least it doesn't result in an error.
=> modulo ref colors

spaceKLIP/analysistools.py, spaceKLIP/imagetools.py
- changed mstar_err to mstar_err_temp in boh tab.add_row calls to be able to parse correctly mstar_err as a dictonaty to the function. This Resolves #193 
- added an annunlus mask to align frame function to mask both inner and outer area of an image
=> Gs annulus mask

.github/workflows/ci_workflows.yml
Update the webbpsf data downlink URL for the CI tests
=> update webbpsf minimal data URL to 1.4.0

docs/source/conf.py
=> Correcting name for webbpsf_ext in mock imports

spaceKLIP/analysistools.py, spaceKLIP/classpsfsubpipeline.py, spaceKLIP/database.py, spaceKLIP/imagetools.py, spaceKLIP/psf.py, spaceKLIP/tests/test_utils.py, spaceKLIP/utils.py
Updated recenter_frames and align_frames to only save the calculated shifts. 
Created a new function shift_frames to apply both shifts at once.
=> Combine image shifts

docs/source/spaceKLIP.rst, requirements.txt, spaceKLIP/__init__.py, spaceKLIP/analysistools.py, spaceKLIP/database.py, spaceKLIP/imagetools.py, spaceKLIP/make_psfmasks.py, spaceKLIP/mast.py, spaceKLIP/psf.py, spaceKLIP/psflib.py, spaceKLIP/tests/test_psflib.py, spaceKLIP/utils.py
Added resample_frames in imagetools to apply distorsion correction to the data
=> Distortion

spaceKLIP/analysistools.py, spaceKLIP/psf.py
Fixes two small typos that are breaking bugs in the `AnalysisTools.extract_companions` workflow.
=> Fix small typos
